# Header
menu:
  소개: /about
  블로그: /
  모아보기: /archives
  Github: https://github.com/joeunha
# rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
#sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
 - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-92829973-1
favicon: /favicon.ico
logo: /images/logo.png
twitter:
google_plus:
fb_admins:
fb_app_id:
